### ISSUE TITLE
SQLServer链接怎么总是显示链接失败

### ISSUE THREAD

**Issue by w21fanfan1314** [xianrendzw/EasyReport#8]
我链接远程的SQLServer测试链接不成功，本地的代码可以链接成功

**Comment by bjxiaowen** [comment]
那我就不清楚你现在的环境配置是什么
原始邮件
发件人:jerrynotifications@github.com
收件人:xianrendzw/EasyReportEasyReport@noreply.github.com
发送时间:2016年11月22日(周二) 18:27
主题:[xianrendzw/EasyReport] SQLServer链接怎么总是显示链接失败 (#8)


我链接远程的SQLServer测试链接不成功，本地的代码可以链接成功

**Comment by w21fanfan1314** [comment]
看到控制台提示，没有找到SQLServer驱动的jar包:
java.sql.SQLException: No suitable driver found for jdbc:sqlserver://xxxxx:20017;DatabaseName=STTX
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.easytoolsoft.easyreport.domain.metadata.service.impl.DataSourceService.testConnection(DataSourceService.java:37)
	at com.easytoolsoft.easyreport.web.controller.metadata.DataSourceController.testConnection(DataSourceController.java:91)
	at com.easytoolsoft.easyreport.web.controller.metadata.DataSourceController$$FastClassBySpringCGLIB$$1bbb2143.invoke(<generated>)

**Comment by w21fanfan1314** [comment]
我添加了jar包还是不行呢~ 郁闷中
